name: Daily TIL

on:
  schedule:
    # Chạy 00:05 Asia/Ho_Chi_Minh (ICT). GitHub Actions dùng UTC, nên 17:05 UTC = 00:05 ICT.
    - cron: '5 17 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  til:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create today's TIL (if missing)
        shell: bash
        run: |
          export TZ=Asia/Ho_Chi_Minh
          today=$(date +%F)
          year=$(date +%Y)
          month=$(date +%m)
          dir="til/$year/$month"
          file="$dir/$today.md"
          mkdir -p "$dir"
          if [ ! -f "$file" ]; then
            cat > "$file" <<'EOF'
# $(date +%F)

- Học được gì:
- Code snippet:
- Link PR/Issue trong ngày:
EOF
            # thay tiêu đề đúng ngày
            sed -i "1 s/.*/# $today/" "$file"
            git add "$file"
          else
            echo "Today's file already exists: $file"
          fi

      - name: Commit & push (if changes)
        shell: bash
        run: |
          export TZ=Asia/Ho_Chi_Minh
          if ! git diff --cached --quiet; then
            git config user.name "${GITHUB_REPOSITORY_OWNER}"
            git config user.email "${GITHUB_REPOSITORY_OWNER}@users.noreply.github.com"
            today=$(date +%F)
            git commit -m "docs(til): add ${today}"
            git push
          else
            echo "No changes to commit"
          fi
