name: Daily TIL

on:
  schedule:
    # 17:05 UTC = 00:05 ICT (VN)
    - cron: '5 17 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  til:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create today's TIL (if missing)
        shell: bash
        run: |
          set -euo pipefail
          export TZ=Asia/Ho_Chi_Minh
          today=$(date +%F)
          year=$(date +%Y)
          month=$(date +%m)
          dir="til/$year/$month"
          file="$dir/$today.md"
          mkdir -p "$dir"
          if [ ! -f "$file" ]; then
            printf '# %s\n\n- Học được gì:\n- Code snippet:\n- Link PR/Issue trong ngày:\n' "$today" > "$file"
            git add "$file"
          else
            echo "Today's file already exists: $file"
          fi

      - name: Commit & push (if changes)
        shell: bash
        run: |
          set -euo pipefail
          if ! git diff --cached --quiet; then
            git config user.name "${GITHUB_REPOSITORY_OWNER}"
            git config user.email "${GITHUB_REPOSITORY_OWNER}@users.noreply.github.com"
            git commit -m "docs(til): add $(date +%F)"
            git push
          else
            echo "No changes to commit"
          fi
