name: Nhật Ký Tự Động Hóa Hàng Ngày

on:
  schedule:
    # Chạy vào 00:05 giờ Việt Nam mỗi ngày (17:05 UTC)
    - cron: '5 17 * * *'
  workflow_dispatch: # Cho phép chạy thủ công

permissions:
  contents: write

concurrency:
  group: daily-note
  cancel-in-progress: true

jobs:
  create-daily-note:
    runs-on: ubuntu-latest
    env:
      CITY: "Ho Chi Minh"
      LAT: "10.82"
      LON: "106.63"
      TZ: Asia/Ho_Chi_Minh

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cập nhật nội dung tự động
        shell: bash
        run: |
          set -euo pipefail
          
          today=$(date +%F)
          file="$today.md"

          if ! command -v jq >/dev/null 2>&1 || ! command -v bc >/dev/null 2>&1; then
            echo "Installing missing tools (jq, bc)..."
            sudo apt-get update -y && sudo apt-get install -y jq bc
          fi

          # ========================================================================
          # === ĐỊNH NGHĨA CÁC HÀM MODULE ==========================================
          # ========================================================================

          function append_header() {
            if [ ! -f "$file" ]; then
              printf '# 🚀 Nhật Ký Tự Động Hóa - %s\n' "$today" > "$file"
            fi
          }

          function append_calendar() {
            if ! grep -q '<!-- CALENDAR-MODULE -->' "$file"; then
              dow_num=$(date +%u); case "$dow_num" in 1) dow="Thứ Hai" ;; 2) dow="Thứ Ba" ;; 3) dow="Thứ Tư" ;; 4) dow="Thứ Năm" ;; 5) dow="Thứ Sáu" ;; 6) dow="Thứ Bảy" ;; 7) dow="Chủ Nhật" ;; esac
              iso_week=$(date +%V); day_of_year=$(date +%j)
              { echo; echo "---"; echo "<!-- CALENDAR-MODULE -->"; echo "## 🗓️ Lịch Hôm Nay"; echo "- **Ngày**: $today ($dow)"; echo "- **Tuần (ISO)**: $iso_week / **Ngày trong năm**: $day_of_year"; } >> "$file"
            fi
          }

          function append_weather_and_uv() {
            if ! grep -q '<!-- WEATHER-UV-MODULE -->' "$file"; then
              wjson=$(curl -fsSL "https://api.open-meteo.com/v1/forecast?latitude=${LAT}&longitude=${LON}&current_weather=true&daily=uv_index_max&timezone=Asia%2FHo_Chi_Minh" || true)
              if [ -n "$wjson" ] && echo "$wjson" | jq -e . >/dev/null 2>&1; then
                temp=$(echo "$wjson" | jq -r '.current_weather.temperature // empty'); wind=$(echo "$wjson" | jq -r '.current_weather.windspeed // empty');
                uv_index=$(echo "$wjson" | jq -r '.daily.uv_index_max[0] // empty' | cut -d'.' -f1)
                { echo; echo "---"; echo "<!-- WEATHER-UV-MODULE -->"; echo "## 🌤️ Thời tiết & Chỉ số UV tại ${CITY}"; echo "- **Nhiệt độ**: ${temp}°C / **Gió**: ${wind} km/h"; if [ -n "$uv_index" ]; then echo "- **Chỉ số UV**: $uv_index"; fi; } >> "$file"
              fi
            fi
          }
          
          function append_cve_news() {
            if ! grep -q '<!-- CVE-MODULE -->' "$file"; then
              cvejson=$(curl -fsSL "https://cve.circl.lu/api/last" || true)
              if [ -n "$cvejson" ] && echo "$cvejson" | jq -e '.[0]' >/dev/null 2>&1; then
                latest_cve=$(echo "$cvejson" | jq '.[0]')
                cve_id=$(echo "$latest_cve" | jq -r '.id')
                cve_summary=$(echo "$latest_cve" | jq -r '.summary')
                { echo; echo "---"; echo "<!-- CVE-MODULE -->"; echo "## 🛡️ Cảnh Báo An Ninh Mạng (CVE)"; echo "- **Mã lỗi**: $cve_id"; echo "- **Tóm tắt**: $cve_summary"; } >> "$file"
              fi
            fi
          }
          
          function append_word_of_the_day() {
            if ! grep -q '<!-- WORD-MODULE -->' "$file"; then
              word=$(curl -fsSL "https://random-word-api.herokuapp.com/word" | jq -r '.[0]')
              if [ -n "$word" ]; then
                defjson=$(curl -fsSL "https://api.dictionaryapi.dev/api/v2/entries/en/${word}" || true)
                if [ -n "$defjson" ] && ! echo "$defjson" | jq -e '.title == "No Definitions Found"'; then
                  definition=$(echo "$defjson" | jq -r '.[0].meanings[0].definitions[0].definition // empty')
                  phonetic=$(echo "$defjson" | jq -r '.[0].phonetic // ""')
                  { echo; echo "---"; echo "<!-- WORD-MODULE -->"; echo "## ✍️ Từ Vựng Truyền Cảm Hứng"; echo "- **Từ**: \`$word\` ($phonetic)"; echo "- **Định nghĩa**: $definition"; } >> "$file"
                fi
              fi
            fi
          }

          function append_game_quote() {
            if ! grep -q '<!-- GAME-QUOTE-MODULE -->' "$file"; then
              gamejson=$(curl -fsSL "https://gaming-quotes.vercel.app/api/random" || true)
              if [ -n "$gamejson" ] && echo "$gamejson" | jq -e . >/dev/null 2>&1; then
                quote=$(echo "$gamejson" | jq -r '.quote')
                author=$(echo "$gamejson" | jq -r '.author')
                { echo; echo "---"; echo "<!-- GAME-QUOTE-MODULE -->"; echo "## 💬 Trích Dẫn Từ Thế Giới Game"; echo "> \"$quote\""; echo ">"; echo "> — ***$author***"; } >> "$file"
              fi
            fi
          }

          function append_art_of_the_day() {
            if ! grep -q '<!-- ART-MODULE -->' "$file"; then
              pagination_json=$(curl -fsSL "https://api.artic.edu/api/v1/artworks/search?query[term][is_public_domain]=true&fields=id&limit=1" || true)
              if [ -n "$pagination_json" ] && echo "$pagination_json" | jq -e . >/dev/null 2>&1; then
                total_pages=$(echo "$pagination_json" | jq -r '.pagination.total_pages // 1000')
                random_page=$((1 + RANDOM % total_pages))
                artjson=$(curl -fsSL "https://api.artic.edu/api/v1/artworks/search?query[term][is_public_domain]=true&fields=id,title,artist_display,image_id&limit=1&page=${random_page}" || true)
                if [ -n "$artjson" ] && [ "$(echo "$artjson" | jq -r '.data | length')" -gt 0 ]; then
                  artwork=$(echo "$artjson" | jq '.data[0]')
                  title=$(echo "$artwork" | jq -r '.title'); artist=$(echo "$artwork" | jq -r '.artist_display' | sed 's/<[^>]*>//g' | cut -d ',' -f 1 | head -n 1); image_id=$(echo "$artwork" | jq -r '.image_id')
                  if [ "$image_id" != "null" ]; then
                    image_url="https://www.artic.edu/iiif/2/${image_id}/full/843,/0/default.jpg"
                    { echo; echo "---"; echo "<!-- ART-MODULE -->"; echo "## 🖼️ Tác Phẩm Nghệ Thuật Trong Ngày"; echo "- **Tên**: $title"; echo "- **Tác giả**: $artist"; echo "![${title}](${image_url})"; } >> "$file"
                  fi
                fi
              fi
            fi
          }

          function append_footer() {
            if ! grep -q '<!-- FOOTER-MODULE -->' "$file"; then
              { echo; echo "---"; echo "<!-- FOOT-MODULE -->"; echo "> *Ghi chú này được tạo tự động bởi [GitHub Actions](https://github.com/features/actions).*" ; } >> "$file"
            fi
          }

          # ========================================================================
          # === GỌI CÁC HÀM ĐỂ THÊM NỘI DUNG =======================================
          # ========================================================================
          echo "Bắt đầu cập nhật file: $file"
          append_header
          append_calendar
          append_weather_and_uv
          append_cve_news
          append_word_of_the_day
          append_game_quote
          append_art_of_the_day
          append_footer
          echo "Hoàn thành cập nhật nội dung."
          
          git add "$file"

      - name: Commit và đẩy code lên repo (nếu có thay đổi)
        id: commit_step
        shell: bash
        run: |
          set -euo pipefail
          if ! git diff --cached --quiet; then
            echo "changes=true" >> $GITHUB_OUTPUT
            git config user.name "${{ github.actor }}"
            git config user.email "${{ github.actor }}@users.noreply.github.com"
            git commit -m "📝 Cập nhật nhật ký tự động ngày $(date +%F)"
            git push
          else
            echo "changes=false" >> $GITHUB_OUTPUT
            echo "Không có gì thay đổi để commit."
          fi

      - name: Gửi thông báo đến Discord
        if: steps.commit_step.outputs.changes == 'true'
        shell: bash
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          if [ -z "$DISCORD_WEBHOOK_URL" ]; then
            echo "Cảnh báo: DISCORD_WEBHOOK_URL secret chưa được thiết lập. Bỏ qua việc gửi thông báo."
            exit 0
          fi
          
          file_url="https://github.com/${{ github.repository }}/blob/${{ github.ref_name }}/$(date +%F).md"
          
          json_payload=$(jq -n \
            --arg title "📝 Nhật Ký Tự Động Hóa - $(date +%F)" \
            --arg url "$file_url" \
            --arg description "File nhật ký cho ngày hôm nay đã được tạo và cập nhật thành công. [Nhấn vào đây để xem]($file_url)" \
            '{
              "username": "GitHub Actions Bot",
              "avatar_url": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
              "embeds": [{
                "title": $title,
                "url": $url,
                "description": $description,
                "color": 3447003,
                "timestamp": "'$(date -u +"%Y-%m-%dT%H:%M:%S.000Z")'"
              }]
            }')

          curl -H "Content-Type: application/json" -d "$json_payload" "$DISCORD_WEBHOOK_URL"

