name: Nhật Ký Tự Động Hóa Hàng Ngày

on:
  schedule:
    # Chạy vào 00:05 giờ Việt Nam mỗi ngày (17:05 UTC)
    - cron: '5 17 * * *'
  workflow_dispatch: # Cho phép chạy thủ công

permissions:
  contents: write

concurrency:
  group: daily-note
  cancel-in-progress: true

jobs:
  create-daily-note:
    runs-on: ubuntu-latest
    env:
      CITY: "Ha Noi"
      LAT: "21.03"
      LON: "105.85"
      TZ: Asia/Ho_Chi_Minh

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cập nhật nội dung tự động
        shell: bash
        run: |
          set -euo pipefail
          
          today=$(date +%F)
          file="$today.md"

          if ! command -v jq >/dev/null 2>&1; then
            echo "jq not found. Installing..."
            sudo apt-get update -y && sudo apt-get install -y jq
          fi

          # ========================================================================
          # === ĐỊNH NGHĨA CÁC HÀM MODULE ==========================================
          # ========================================================================

          function append_header() {
            if [ ! -f "$file" ]; then
              printf '# 🚀 Nhật Ký Tự Động Hóa - %s\n' "$today" > "$file"
            fi
          }

          function append_calendar() {
            if ! grep -q '<!-- CALENDAR-MODULE -->' "$file"; then
              dow_num=$(date +%u); case "$dow_num" in 1) dow="Thứ Hai" ;; 2) dow="Thứ Ba" ;; 3) dow="Thứ Tư" ;; 4) dow="Thứ Năm" ;; 5) dow="Thứ Sáu" ;; 6) dow="Thứ Bảy" ;; 7) dow="Chủ Nhật" ;; esac
              iso_week=$(date +%V); day_of_year=$(date +%j)
              { echo; echo "---"; echo "<!-- CALENDAR-MODULE -->"; echo "## 🗓️ Lịch Hôm Nay"; echo "- **Ngày**: $today ($dow)"; echo "- **Tuần (ISO)**: $iso_week / **Ngày trong năm**: $day_of_year"; } >> "$file"
            fi
          }

          function append_weather_and_uv() {
            if ! grep -q '<!-- WEATHER-UV-MODULE -->' "$file"; then
              wjson=$(curl -fsSL "https://api.open-meteo.com/v1/forecast?latitude=${LAT}&longitude=${LON}&current_weather=true&daily=uv_index_max&timezone=Asia%2FHo_Chi_Minh" || true)
              if [ -n "$wjson" ] && echo "$wjson" | jq -e . >/dev/null 2>&1; then
                temp=$(echo "$wjson" | jq -r '.current_weather.temperature // empty'); wind=$(echo "$wjson" | jq -r '.current_weather.windspeed // empty'); code=$(echo "$wjson" | jq -r '.current_weather.weathercode // empty'); desc="Không rõ"
                case "$code" in 0) desc="Trời quang mây" ;; 1|2|3) desc="Ít mây / Nhiều mây" ;; 45|48) desc="Sương mù" ;; 51|53|55) desc="Mưa phùn" ;; 61|63|65) desc="Mưa vừa/đậm" ;; 80|81|82) desc="Mưa rào" ;; 95) desc="Dông" ;; *) desc="Không xác định" ;; esac
                
                uv_index=$(echo "$wjson" | jq -r '.daily.uv_index_max[0] // empty' | cut -d'.' -f1)
                uv_desc="Không xác định"
                if [ -n "$uv_index" ]; then
                    if (( uv_index <= 2 )); then uv_desc="Thấp - Không cần bảo vệ"
                    elif (( uv_index <= 5 )); then uv_desc="Trung bình - Cần che chắn"
                    elif (( uv_index <= 7 )); then uv_desc="Cao - Cần bôi kem chống nắng"
                    elif (( uv_index <= 10 )); then uv_desc="Rất cao - Hạn chế ra ngoài"
                    else uv_desc="Cực kỳ cao - Tránh ra ngoài trời"
                    fi
                fi

                { 
                  echo; echo "---"; echo "<!-- WEATHER-UV-MODULE -->"; echo "## 🌤️ Thời tiết & Chỉ số UV tại ${CITY}"
                  if [ -n "${temp}" ]; then echo "- **Nhiệt độ**: ${temp}°C"; echo "- **Gió**: ${wind} km/h"; echo "- **Hiện tượng**: ${desc}"; else echo "- (Không lấy được dữ liệu thời tiết)"; fi
                  if [ -n "$uv_index" ]; then echo "- **Chỉ số UV**: $uv_index ($uv_desc)"; fi
                } >> "$file"
              else
                echo "Cảnh báo: API Thời tiết/UV thất bại. Bỏ qua module này."
              fi
            fi
          }

          function append_financial_data() {
            if ! grep -q '<!-- FINANCE-MODULE -->' "$file"; then
              ratejson=$(curl --connect-timeout 5 -fsSL "https://open.er-api.com/v6/latest/USD" || true)
              goldjson=$(curl --connect-timeout 5 -fsSL "https://vapi.vnappmob.com/api/v2/gold" || true) # API VÀNG MỚI
              usd_vnd_rate="Đang cập nhật..."; gold_sell="Đang cập nhật..."
              if [ -n "$ratejson" ] && echo "$ratejson" | jq -e . >/dev/null 2>&1; then
                  usd_vnd_rate=$(echo "$ratejson" | jq '.rates.VND | tonumber | printf "%.0f"' 2>/dev/null || echo "Lỗi")
              fi
              if [ -n "$goldjson" ] && echo "$goldjson" | jq -e '.results' >/dev/null 2>&1; then
                  gold_sell_raw=$(echo "$goldjson" | jq -r '.results[] | select(.name | contains("SJC")) | .sell' | head -n 1)
                  if [ -n "$gold_sell_raw" ]; then
                    gold_sell=$(printf "%.3f" $(echo "$gold_sell_raw / 1000000" | bc -l))
                    gold_sell="${gold_sell} triệu"
                  fi
              fi
              { echo; echo "---"; echo "<!-- FINANCE-MODULE -->"; echo "## 💰 Dữ liệu tài chính"; echo "- **Tỷ giá USD/VND**: 1 USD ≈ $usd_vnd_rate VND"; echo "- **Vàng SJC (bán ra)**: $gold_sell / lượng"; } >> "$file"
            fi
          }
          
          function append_crypto_prices() {
            if ! grep -q '<!-- CRYPTO-MODULE -->' "$file"; then
              cryptojson=$(curl -fsSL "https://api.coingecko.com/api/v3/simple/price?ids=bitcoin,ethereum&vs_currencies=usd" || true)
              if [ -n "$cryptojson" ] && echo "$cryptojson" | jq -e . >/dev/null 2>&1; then
                btc_price=$(echo "$cryptojson" | jq -r '.bitcoin.usd | tonumber | printf "%.2f"')
                eth_price=$(echo "$cryptojson" | jq -r '.ethereum.usd | tonumber | printf "%.2f"')
                { echo; echo "---"; echo "<!-- CRYPTO-MODULE -->"; echo "## 📈 Giá Tiền Mã Hóa"; echo "- **Bitcoin (BTC)**: \$${btc_price} USD"; echo "- **Ethereum (ETH)**: \$${eth_price} USD"; } >> "$file"
              fi
            fi
          }
          
          function append_enchantment_idea() {
            if ! grep -q '<!-- ENCHANTMENT-MODULE -->' "$file"; then
              IDEAS_ARRAY=(
                "**Tên**: Sét Đánh Trả | **Hiệu ứng**: Khi bị tấn công, có 10% cơ hội gọi một tia sét xuống kẻ tấn công. | **Áp dụng cho**: Giáp"
                "**Tên**: Hút Sinh Lực | **Hiệu ứng**: Mỗi đòn đánh hồi lại 5% sát thương gây ra thành máu. | **Áp dụng cho**: Vũ khí cận chiến"
                "**Tên**: Đạn Xuyên Thấu | **Hiệu ứng**: Mũi tên bắn ra có thể xuyên qua tối đa 2 mục tiêu, gây 75% sát thương cho mục tiêu thứ hai. | **Áp dụng cho**: Cung"
                "**Tên**: Bước Chân Băng Giá | **Hiệu ứng**: Tạo ra một vệt băng tạm thời trên mặt nước khi di chuyển. | **Áp dụng cho**: Giày"
                "**Tên**: Lưỡi Kiếm Độc Tố | **Hiệu ứng**: Đòn đánh có 20% cơ hội gây hiệu ứng Độc II trong 5 giây. | **Áp dụng cho**: Kiếm"
              )
              day_of_year=$(date +%j); day_of_year=$((10#$day_of_year)); len=${#IDEAS_ARRAY[@]}; idx=$(( (day_of_year - 1) % len )); idea="${IDEAS_ARRAY[$idx]}"
              { echo; echo "---"; echo "<!-- ENCHANTMENT-MODULE -->"; echo "## 🪄 Ý Tưởng Enchantment"; echo "> $idea"; } >> "$file"
            fi
          }
          
          function append_art_of_the_day() {
            if ! grep -q '<!-- ART-MODULE -->' "$file"; then
              # Lấy một tác phẩm ngẫu nhiên từ 1000 trang đầu tiên
              random_page=$((1 + RANDOM % 1000))
              artjson=$(curl -fsSL "https://api.artic.edu/api/v1/artworks/search?query[term][is_public_domain]=true&fields=id,title,artist_display,image_id&limit=1&page=${random_page}" || true)
              if [ -n "$artjson" ] && [ "$(echo "$artjson" | jq -r '.data | length')" -gt 0 ]; then
                title=$(echo "$artjson" | jq -r '.data[0].title'); artist=$(echo "$artjson" | jq -r '.data[0].artist_display'); image_id=$(echo "$artjson" | jq -r '.data[0].image_id')
                if [ "$image_id" != "null" ]; then
                  image_url="https://www.artic.edu/iiif/2/${image_id}/full/843,/0/default.jpg"
                  { echo; echo "---"; echo "<!-- ART-MODULE -->"; echo "## 🖼️ Tác Phẩm Nghệ Thuật Trong Ngày"; echo "- **Tên**: $title"; echo "- **Tác giả**: $artist"; echo "![${title}](${image_url})"; } >> "$file"
                fi
              fi
            fi
          }

          function append_footer() {
            if ! grep -q '<!-- FOOTER-MODULE -->' "$file"; then
              { echo; echo "---"; echo "<!-- FOOTER-MODULE -->"; echo "> *Ghi chú này được tạo tự động bởi [GitHub Actions](https://github.com/features/actions).*" ; } >> "$file"
            fi
          }

          # ========================================================================
          # === GỌI CÁC HÀM ĐỂ THÊM NỘI DUNG =======================================
          # ========================================================================
          echo "Bắt đầu cập nhật file: $file"
          append_header
          append_calendar
          append_weather_and_uv
          append_financial_data
          append_crypto_prices
          append_enchantment_idea
          append_art_of_the_day
          append_footer
          echo "Hoàn thành cập nhật nội dung."
          
          git add "$file"

      - name: Commit và đẩy code lên repo (nếu có thay đổi)
        shell: bash
        run: |
          set -euo pipefail
          if ! git diff --cached --quiet; then
            git config user.name "${{ github.actor }}"
            git config user.email "${{ github.actor }}@users.noreply.github.com"
            git commit -m "📝 Cập nhật nhật ký tự động ngày $(date +%F)"
            git push
          else
            echo "Không có gì thay đổi để commit."
          fi

