name: Daily TIL

on:
  schedule:
    - cron: '5 17 * * *'  # 17:05 UTC = 00:05 ICT
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: daily-til
  cancel-in-progress: true

jobs:
  til:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create today's TIL (if missing)
        shell: bash
        run: |
          set -euo pipefail
          export TZ=Asia/Ho_Chi_Minh
          today=$(date +%F)
          year=$(date +%Y)
          month=$(date +%m)
          dir="til/$year/$month"
          file="$dir/$today.md"
          mkdir -p "$dir"
          if [ ! -f "$file" ]; then
            printf '# %s\n' "$today" > "$file"
            git add "$file"
          else
            echo "Today's file already exists: $file"
          fi

      - name: Append modules (Calendar + Kata + Weather)
        shell: bash
        env:
          CITY: "Ha Noi"
          LAT: "21.03"
          LON: "105.85"
        run: |
          set -euo pipefail
          export TZ=Asia/Ho_Chi_Minh

          # Today's file
          today=$(date +%F)
          year=$(date +%Y); month=$(date +%m)
          file="til/$year/$month/$today.md"
          [ -f "$file" ] || printf '# %s\n' "$today" > "$file"

          # jq (if missing)
          if ! command -v jq >/dev/null 2>&1; then
            sudo apt-get update -y && sudo apt-get install -y jq
          fi

          # --- Module 1: Calendar (offline, idempotent)
          if ! grep -q '^<!-- MOD-1-CALENDAR -->$' "$file"; then
            dow_num=$(date +%u)
            case "$dow_num" in
              1) dow="Thứ Hai" ;;
              2) dow="Thứ Ba" ;;
              3) dow="Thứ Tư" ;;
              4) dow="Thứ Năm" ;;
              5) dow="Thứ Sáu" ;;
              6) dow="Thứ Bảy" ;;
              7) dow="Chủ Nhật" ;;
            esac
            iso_week=$(date +%V)
            day_of_year=$(date +%j)
            {
              echo
              echo "<!-- MOD-1-CALENDAR -->"
              echo "## Hom nay"
              echo "- Ngay: $today ($dow)"
              echo "- Tuan ISO: $iso_week — DayOfYear: $day_of_year"
            } >> "$file"
          fi

          # --- Module 7: Mini-kata (offline deck)
          if ! grep -q '^<!-- MOD-7-KATA -->$' "$file"; then
            KATA_ARR=(
              'Implement a function `dedupe_keep_order(arr)` (Python) loai phan tu trung, giu nguyen thu tu.'
              'Write `flattenN(arr, n)` (JS) phang mang long toi da do sau n.'
              'Viet `is_palindrome(s)` (Python) bo qua ky tu khong chu/so & khong phan biet hoa thuong.'
              'Implement `throttle(fn, wait)` (JS) tra ve ham chi chay toi da 1 lan moi wait ms.'
              'Viet `fib_gen(n)` (Python) generator yield n so Fibonacci dau tien (khong dung de quy).'
              'Implement `formatVND(n)` (JS) tra ve chuoi tien te VND (Intl.NumberFormat neu co).'
              'Viet `count_status(logs)` (Python) tra ve dict {status: count} tu danh sach log HTTP.'
              'Implement `uniqueBy(arr, key)` (JS) loai trung theo khoa (string hoac accessor fn).'
              'Viet `two_sum(nums, target)` (Python) tra ve cap chi so i,j sao cho nums[i]+nums[j]=target.'
              'Implement `groupBy(arr, key)` (JS) nhom phan tu theo thuoc tinh/khoa.'
            )
            doy=$(date +%j); doy=$((10#$doy))
            len=${#KATA_ARR[@]}
            idx=$(( (doy - 1) % len ))
            kata="${KATA_ARR[$idx]}"
            {
              echo
              echo "<!-- MOD-7-KATA -->"
              echo "## Mini-kata"
              echo "- $kata"
              echo
              echo "Go i y khoi dau:"
              echo '```python'
              echo '# TODO: giai o day'
              echo '```'
            } >> "$file"
          fi

          # --- Module 15: Weather (Open-Meteo, no key)
          if ! grep -q '^<!-- MOD-15-WEATHER -->$' "$file"; then
            wjson=$(curl -fsSL "https://api.open-meteo.com/v1/forecast?latitude=${LAT}&longitude=${LON}&current_weather=true&timezone=Asia%2FHo_Chi_Minh" || true)
            if [ -n "$wjson" ]; then
              temp=$(echo "$wjson" | jq -r '.current_weather.temperature // empty')
              wind=$(echo "$wjson" | jq -r '.current_weather.windspeed // empty')
              code=$(echo "$wjson" | jq -r '.current_weather.weathercode // empty')
              desc="Khong ro"
              case "$code" in
                0) desc="Troi quang may" ;;
                1|2|3) desc="It may / Nhieu may" ;;
                45|48) desc="Suong mu" ;;
                51|53|55) desc="Mua phun" ;;
                61|63|65) desc="Mua vua/dam" ;;
                71|73|75) desc="Tuyet roi" ;;
                80|81|82) desc="Mua rao" ;;
                95) desc="Dong" ;;
                96|99) desc="Dong kem mua da" ;;
              esac
              {
                echo
                echo "<!-- MOD-15-WEATHER -->"
                echo "## Thoi tiet $CITY (hien tai)"
                if [ -n "${temp}" ] && [ -n "${wind}" ] && [ -n "${code}" ]; then
                  echo "- Nhiet do: ${temp}°C"
                  echo "- Gio: ${wind} km/h"
                  echo "- Ma/ Dien giai: ${code} — ${desc}"
                else
                  echo "- (Khong lay duoc du lieu)"
                fi
              } >> "$file"
            fi
          fi

          git add "$file"

      - name: Commit & push (if changes)
        shell: bash
        run: |
          set -euo pipefail
          if ! git diff --cached --quiet; then
            git config user.name "${{ github.actor }}"
            git config user.email "${{ github.actor }}@users.noreply.github.com"
            git commit -m "chore(til): daily autosummary"
            git push
          else
            echo "No changes to commit"
          fi
