name: Nhật Ký Tự Động Hóa Hàng Ngày

on:
  schedule:
    # Chạy vào 00:05 giờ Việt Nam mỗi ngày (17:05 UTC)
    - cron: '5 17 * * *'
  workflow_dispatch: # Cho phép chạy thủ công

permissions:
  contents: write

concurrency:
  group: daily-note
  cancel-in-progress: true

jobs:
  create-daily-note:
    runs-on: ubuntu-latest
    env:
      CITY: "Ha Noi"
      LAT: "21.03"
      LON: "105.85"
      TZ: Asia/Ho_Chi_Minh

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cập nhật nội dung tự động
        shell: bash
        run: |
          set -euo pipefail
          
          # --- ĐỊNH NGHĨA TÊN FILE TẠI THƯ MỤC GỐC ---
          today=$(date +%F)
          file="$today.md"

          # --- Cài đặt công cụ cần thiết (nếu thiếu) ---
          if ! command -v jq >/dev/null 2>&1; then
            echo "jq not found. Installing..."
            sudo apt-get update -y && sudo apt-get install -y jq
          fi

          # ========================================================================
          # === ĐỊNH NGHĨA CÁC HÀM MODULE (PHIÊN BẢN BỀN BỈ HƠN) ===================
          # ========================================================================

          function append_header() {
            if [ ! -f "$file" ]; then
              printf '# 🚀 Nhật Ký Tự Động Hóa - %s\n' "$today" > "$file"
            fi
          }

          function append_calendar() {
            if ! grep -q '<!-- CALENDAR-MODULE -->' "$file"; then
              dow_num=$(date +%u); case "$dow_num" in 1) dow="Thứ Hai" ;; 2) dow="Thứ Ba" ;; 3) dow="Thứ Tư" ;; 4) dow="Thứ Năm" ;; 5) dow="Thứ Sáu" ;; 6) dow="Thứ Bảy" ;; 7) dow="Chủ Nhật" ;; esac
              iso_week=$(date +%V); day_of_year=$(date +%j)
              { echo; echo "---"; echo "<!-- CALENDAR-MODULE -->"; echo "## 🗓️ Lịch Hôm Nay"; echo "- **Ngày**: $today ($dow)"; echo "- **Tuần (ISO)**: $iso_week / **Ngày trong năm**: $day_of_year"; } >> "$file"
            fi
          }

          function append_lunar_calendar() {
            if ! grep -q '<!-- LUNAR-MODULE -->' "$file"; then
              day=$(date +%d); month=$(date +%m); year=$(date +%Y)
              lunarjson=$(curl -fsSL "https://api.bebi.dev/lich-am?day=${day}&month=${month}&year=${year}" || true)
              if [ -n "$lunarjson" ] && echo "$lunarjson" | jq -e . >/dev/null 2>&1; then
                amlich=$(echo "$lunarjson" | jq -r '"\(.day)/\(.month)/\(.year)"'); canchi=$(echo "$lunarjson" | jq -r '"Ngày \(.day_can_chi), tháng \(.month_can_chi), năm \(.year_can_chi)"')
                { echo; echo "<!-- LUNAR-MODULE -->"; echo "## 🌕 Lịch Âm"; echo "- **Âm lịch**: $amlich"; echo "- **Can Chi**: $canchi"; } >> "$file"
              else
                echo "Cảnh báo: API Lịch Âm (api.bebi.dev) thất bại. Bỏ qua module này."
              fi
            fi
          }

          function append_weather() {
            if ! grep -q '<!-- WEATHER-MODULE -->' "$file"; then
              wjson=$(curl -fsSL "https://api.open-meteo.com/v1/forecast?latitude=${LAT}&longitude=${LON}&current_weather=true&timezone=Asia%2FHo_Chi_Minh" || true)
              if [ -n "$wjson" ] && echo "$wjson" | jq -e . >/dev/null 2>&1; then
                temp=$(echo "$wjson" | jq -r '.current_weather.temperature // empty'); wind=$(echo "$wjson" | jq -r '.current_weather.windspeed // empty'); code=$(echo "$wjson" | jq -r '.current_weather.weathercode // empty'); desc="Không rõ"
                case "$code" in 0) desc="Trời quang mây" ;; 1|2|3) desc="Ít mây / Nhiều mây" ;; 45|48) desc="Sương mù" ;; 51|53|55) desc="Mưa phùn" ;; 61|63|65) desc="Mưa vừa/đậm" ;; 80|81|82) desc="Mưa rào" ;; 95) desc="Dông" ;; *) desc="Không xác định" ;; esac
                { echo; echo "---"; echo "<!-- WEATHER-MODULE -->"; echo "## 🌤️ Thời tiết tại ${CITY}"; if [ -n "${temp}" ]; then echo "- **Nhiệt độ**: ${temp}°C"; echo "- **Gió**: ${wind} km/h"; echo "- **Hiện tượng**: ${desc}"; else echo "- (Không lấy được dữ liệu thời tiết)"; fi; } >> "$file"
              else
                echo "Cảnh báo: API Thời tiết (api.open-meteo.com) thất bại. Bỏ qua module này."
              fi
            fi
          }

          function append_financial_data() {
            if ! grep -q '<!-- FINANCE-MODULE -->' "$file"; then
              ratejson=$(curl --connect-timeout 5 -fsSL "https://open.er-api.com/v6/latest/USD" || true)
              goldjson=$(curl --connect-timeout 5 -fsSL "https://api-gold.vercel.app/api/sjc" || true)
              usd_vnd_rate="Đang cập nhật..."; gold_sell="Đang cập nhật..."
              if [ -n "$ratejson" ] && echo "$ratejson" | jq -e . >/dev/null 2>&1; then
                  usd_vnd_rate=$(echo "$ratejson" | jq '.rates.VND | tonumber | printf "%.0f"' 2>/dev/null || echo "Lỗi")
              fi
              if [ -n "$goldjson" ] && echo "$goldjson" | jq -e . >/dev/null 2>&1; then
                  latest_gold=$(echo "$goldjson" | jq '.[0]'); gold_sell=$(echo "$latest_gold" | jq -r '.sell | tonumber / 1000 | tostring + " triệu"')
              fi
              { echo; echo "---"; echo "<!-- FINANCE-MODULE -->"; echo "## 💰 Dữ liệu tài chính"; echo "- **Tỷ giá USD/VND**: 1 USD ≈ $usd_vnd_rate VND"; echo "- **Vàng SJC (bán ra)**: $gold_sell / lượng"; } >> "$file"
            fi
          }
          
          function append_hacker_news() {
            if ! grep -q '<!-- HACKERNEWS-MODULE -->' "$file"; then
              hnjson=$(curl -fsSL "https://hn.algolia.com/api/v1/search?tags=front_page&hitsPerPage=3" || true)
              if [ -n "$hnjson" ] && echo "$hnjson" | jq -e . >/dev/null 2>&1; then 
                { echo; echo "---"; echo "<!-- HACKERNEWS-MODULE -->"; echo "## 📰 Top tin tức Hacker News"; echo "$hnjson" | jq -r '.hits[] | "- [\(.title)](\(.url))"'; } >> "$file"
              fi
            fi
          }

          function append_history() {
            if ! grep -q '<!-- HISTORY-MODULE -->' "$file"; then
              month=$(date +%m); day=$(date +%d)
              histjson=$(curl -fsSL "https://en.wikipedia.org/api/rest_v1/feed/onthisday/events/${month}/${day}" || true)
              if [ -n "$histjson" ] && echo "$histjson" | jq -e . >/dev/null 2>&1; then 
                { echo; echo "---"; echo "<!-- HISTORY-MODULE -->"; echo "## 📜 Sự kiện lịch sử trong ngày"; echo "$histjson" | jq -r '.events[0:3][] | "- **\(.year)**: \(.text)"'; } >> "$file"
              fi
            fi
          }
          
          function append_quote() {
            if ! grep -q '<!-- QUOTE-MODULE -->' "$file"; then
              qjson=$(curl -fsSL "https://api.quotable.io/random" || true)
              if [ -n "$qjson" ] && echo "$qjson" | jq -e . >/dev/null 2>&1; then
                content=$(echo "$qjson" | jq -r '.content // empty'); author=$(echo "$qjson" | jq -r '.author // empty')
                { echo; echo "---"; echo "<!-- QUOTE-MODULE -->"; echo "## 💬 Trích dẫn trong ngày"; if [ -n "$content" ]; then echo "> $content"; echo ">"; echo "> — ***$author***"; else echo "- (Không lấy được dữ liệu)"; fi; } >> "$file"
              fi
            fi
          }

          function append_joke() {
            if ! grep -q '<!-- JOKE-MODULE -->' "$file"; then
              jokejson=$(curl -fsSL "https://readme-jokes.vercel.app/api" || true)
              if [ -n "$jokejson" ] && echo "$jokejson" | jq -e . >/dev/null 2>&1; then
                setup=$(echo "$jokejson" | jq -r '.setup'); punchline=$(echo "$jokejson" | jq -r '.punchline')
                { echo; echo "---"; echo "<!-- JOKE-MODULE -->"; echo "## 😂 Chuyện cười DEV"; echo "**Hỏi:** *$setup*"; echo "**Đáp:** *$punchline*"; } >> "$file"
              fi
            fi
          }

          function append_footer() {
            if ! grep -q '<!-- FOOTER-MODULE -->' "$file"; then
              { echo; echo "---"; echo "<!-- FOOTER-MODULE -->"; echo "> *Ghi chú này được tạo tự động bởi [GitHub Actions](https://github.com/features/actions).*" ; } >> "$file"
            fi
          }

          # ========================================================================
          # === GỌI CÁC HÀM ĐỂ THÊM NỘI DUNG =======================================
          # ========================================================================
          echo "Bắt đầu cập nhật file: $file"
          append_header
          append_calendar
          append_lunar_calendar
          append_weather
          append_financial_data
          append_hacker_news
          append_history
          append_quote
          append_joke
          append_footer
          echo "Hoàn thành cập nhật nội dung."

          # --- Thêm file vào staging area để chuẩn bị commit ---
          git add "$file"

      - name: Commit và đẩy code lên repo (nếu có thay đổi)
        shell: bash
        run: |
          set -euo pipefail
          if ! git diff --cached --quiet; then
            git config user.name "${{ github.actor }}"
            git config user.email "${{ github.actor }}@users.noreply.github.com"
            git commit -m "📝 Cập nhật nhật ký tự động ngày $(date +%F)"
            git push
          else
            echo "Không có gì thay đổi để commit."
          fi

